# Generated by Django 3.1.4 on 2020-12-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_alternative',
            name='PALMProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_Product', to='product.product', verbose_name='Product'),
        ),
    ]
