# Generated by Django 3.1.4 on 2020-12-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_prdslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDdiscoundPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='discound price'),
            preserve_default=False,
        ),
    ]
