# Generated by Django 3.1.4 on 2020-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_prddiscoundprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDbestseller',
            field=models.BooleanField(default=False, verbose_name='bestseller'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDisnew',
            field=models.BooleanField(default=True, verbose_name='isnew'),
        ),
    ]
