# Generated by Django 3.1.4 on 2020-12-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201227_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDslug',
            field=models.SlugField(blank=True, null=True, verbose_name='Product url'),
        ),
        migrations.AlterField(
            model_name='product_accessory',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_Product', to='product.product', verbose_name='Product'),
        ),
    ]
